local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"

function data()

return { 
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo platform"),
		description = _("Platform for waiting cargo."),
		icon = "ui/construction/station/street/platform_cargo.tga"
	}, 
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	type = "street_terminal_cargo",
	order = {
		value = 6,
	},
	metadata = {
		cargo = true,
	},
	
	updateFn = function(result, transform, tag, slotId, addModelFn, params)
	
		local coordI, coordJ, variant = result.DemangleId(slotId)
		
		local right = coordI >= 0

		if right then 
			addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_rep.mdl", transf.transl(vec3.new(.0, .0, .0)))
		else 
			addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_l_rep.mdl", transf.transl(vec3.new(.0, .0, .0)))
		end
		
		if params.modules[result.MangleId({coordI, right and coordJ + 1 or coordJ - 1, 1})] == nil then
			addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_top.mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(.0, .0, .0)))
		end
		if params.modules[result.MangleId({coordI, right and coordJ - 1 or coordJ + 1, 1})] == nil then
			addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_btm.mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(.0, .0, .0)))
		end
		
		addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_path_rep" .. result.cat .. ".mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(right and -7.5 or 7.5, .0, .0)))
		result.coord2terminalInfo[coordI][coordJ] = {
			model = #result.models - 1,
			terminal = 0,
		}
	end,
	
	getModelsFn = function()
		
		local result = {
			{ 
				id = "station/road/streetstation/era_a/cargo_pltfrm_r_top.mdl",
				transf = transf.transl(vec3.new(.0, .0, .0)),
			},
			{ 
				id = "station/road/streetstation/era_a/cargo_pltfrm_r_rep.mdl",
				transf = transf.transl(vec3.new(.0, .0, .0)),
			},
			{ 
				id = "station/road/streetstation/era_a/cargo_pltfrm_r_btm.mdl",
				transf = transf.transl(vec3.new(.0, .0, .0)),
			},
		}
		
		return result
	end
}

end
