local transf = require "transf"
local vec3 = require "vec3"
local vec4 = require "vec4"
local colliderutil = require "colliderutil"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"

--Begin Generated
local generatedData = {
	["era_c_airport_runway_permanent"] = {
		models = {
			["station/air/airport/era_c_sm_runway.mdl"] = {
				{ 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, },
			},
		},
	},
}
--End Generated

function data()

return { 
	description = {
		icon = "ui/construction/station/air/landing_c.tga",
		name = _("Approach lights"),
		description = _("Determines the approach and takeoff direction of the runway."),
	},
	category = {
		categories = {"misc"},
	},
	availability = {
		yearFrom = 1980,
		yearTo = 0,
	},
	type = "landing_a",
	order = {
		value = 1000,
	},
	
	updateFn = function(result, transform, tag)
		result.models[#result.models + 1] = { 
			id = "station/air/asset/approach_light_rabbit_c.mdl",
			transf = transform,
			tag = tag
		}
		
		local center = modulesutil.mul(transform, {30.0, 0.0, -1.0, 1.0})
		table.insert(result.colliders, 
			colliderutil.createBox(center, { 30, 9, 3 })
		)
		
		local mainGroundDimX = {0, 60}
		local mainGroundDimY = {-15, 15}
		local mainGroundDimX2 = {60, 120}
		local mainGroundDimY2 = {-3, 3}
		
		local terrain_faces2 = {
			{
				type = "EQUAL",
				faces = {
					{ 
						{mainGroundDimX[1], mainGroundDimY[1], 0, 1}, {mainGroundDimX[2], mainGroundDimY[1], 0, 1}, 
						{mainGroundDimX[2], mainGroundDimY[2], 0, 1}, {mainGroundDimX[1], mainGroundDimY[2], 0, 1}
					},
					{ 
						{mainGroundDimX2[1], mainGroundDimY2[1], 0, 1}, {mainGroundDimX2[2], mainGroundDimY2[1], 0, 1}, 
						{mainGroundDimX2[2], mainGroundDimY2[2], 0, 1}, {mainGroundDimX2[1], mainGroundDimY2[2], 0, 1}
					}
				},
				slopeLow = 0.275,
				slopeHigh = 0.6
			}
		}
		modulesutil.TransformAlignmentFaces(transform, terrain_faces2)
		table.insert(result.terrainAlignmentLists, terrain_faces2[1])
		
		table.insert(result.groundFaces, {  
			face = terrain_faces2[1].faces[1],
			modes = {
				{
					type = "FILL",
					key = "none.lua",
					texCoords = { {1.0, .0}, {1.0, 1.0}, {.0, 1.0}, {.0, .0} }
				}
			}
		})
		table.insert(result.groundFaces, {  
			face = terrain_faces2[1].faces[2],
			modes = {
				{
					type = "FILL",
					key = "none.lua",
					texCoords = { {1.0, .0}, {1.0, 1.0}, {.0, 1.0}, {.0, .0} }
				}
			}
		})
		constructionutil.addModels(generatedData["era_c_airport_runway_permanent"], result.models, transform)
	end,
	
	getModelsFn = function()
		
		local result = {
			{ 
				id = "station/air/asset/approach_light_rabbit_c.mdl",
				transf = transf.scale(vec3.new(1, 1, 1)),
			}
		}
		
		return result
	end
}

end
